[package]
name = "edda_templates"
version = "0.1.0"
edition = "2024"

[dependencies]
rust-embed = { version = "8.8.0", features = ["include-exclude"] }
eyre = "0.6"
ignore = "0.4"
imara-diff = { version = "0.2", features = ["unified_diff"] }
