[package]
name = "rust_impl"
version = "0.1.0"
edition = "2021"

[lib]
name = "_rust_impl"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"] }
numpy = "0.22"
